# based on Patina's workflow
name: Build
on: [ push, pull_request ]
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - name: Pull Gradle Cache
        uses: actions/cache@v3
        id: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-maven-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-java-${{ matrix.java }}
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
      - name: Patch
        run: |
          ./gradlew applyPatches --stacktrace --no-daemon
      - name: Get MC Version
        run: echo "::set-output name=mcver::$(grep mcVersion gradle.properties | awk '{print $3;}')"
        id: mcver
      - name: Build
        run: |
          ./gradlew createReobfPaperclipJar --stacktrace --no-daemon
      - name: Archive Paperclip
        uses: actions/upload-artifact@v4
        with:
          name: Interstellar
          path: build/libs/interstellar-paperclip-${{ steps.mcver.outputs.mcver }}-R0.1-SNAPSHOT-reobf.jar
